/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smartsensor' at '5/18/17 5:23 PM' with Gradle 3.0
 *
 * @author smartsensor, @date 5/18/17 5:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
